typography_spectrum: 0.0893002301454544
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.9859060109592974
  lightness: 0.9240582354832441
  saturation: 0.019072828581556678
  rhythmicContrast: 0.8740761836525053
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6729429725091904
analytics:
  google: null
  facebook: null
  twitter: null
name: liecht
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Nacht, Stadt, überall'
    id: 679cd308-fdca-4860-bcbf-0320dcc6b256
    type: content
  - name: 'Feierabend, Los Angeles Miniature, Farbenschlieren'
    id: ba05c582-6e85-474c-a4c4-388efb418a05
    type: content
  - name: 'Morgen, Schnee, Fünf'
    id: 21e58cfb-d827-45d4-90fe-20e573113080
    type: content
favicon: null
title: liecht
purpose: []
